sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xietian337
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: tiantianlearing
